services:
  iec104-server:
    build: ./server
    container_name: iec104-server
    ports:
      - "2404:2404"
    networks:
      - iec104-net

  iec104-client:
    build: ./client
    container_name: iec104-client
    depends_on:
      - iec104-server
    environment:
      - IEC104_SERVER_HOST=iec104-server
    networks:
      - iec104-net
    command: sh -c "sleep 3 && python client.py"

networks:
  iec104-net:
    driver: bridge