services:
  iec104-server:
    build: ./server
    network_mode: host

  iec104-client:
    build: ./client
    network_mode: host
    depends_on:
      - iec104-server
    command: sh -c "sleep 2 && python client_demo.py"