services:
  iec104-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "2404:2404"

  iec104-client:
    build:
      context: .
      dockerfile: client/Dockerfile

